
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzersJSON;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 8;
  public static final int LEFT_CURLY_BRACKET = 2;
  public static final int COLON = 7;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int RIGHT_CURLY_BRACKET = 3;
  public static final int LEFT_SQUARE_BRACKET = 4;
  public static final int RIGHT_SQUARE_BRACKET = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LEFT_CURLY_BRACKET",
  "RIGHT_CURLY_BRACKET",
  "LEFT_SQUARE_BRACKET",
  "RIGHT_SQUARE_BRACKET",
  "COMMA",
  "COLON",
  "DECIMAL",
  "STRING"
  };
}

