
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREASE = 49;
  public static final int DIVIDE = 32;
  public static final int NOT_EQUAL_TO = 45;
  public static final int CHAR = 23;
  public static final int PERIOD = 46;
  public static final int RIGHT_SQUARE_BRACKET = 38;
  public static final int CASE = 7;
  public static final int DOUBLE = 22;
  public static final int INTEGER = 16;
  public static final int INT = 21;
  public static final int FOR = 10;
  public static final int MINUS = 30;
  public static final int GREATER_THAN = 40;
  public static final int WRITE = 14;
  public static final int CHARACTER = 18;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int OR = 27;
  public static final int BOOL = 24;
  public static final int LESS_EQUAL = 41;
  public static final int RIGHT_PARENTHESIS = 34;
  public static final int PLUS = 29;
  public static final int LEFT_CURLY_BRACKET = 35;
  public static final int MAIN = 3;
  public static final int IF = 4;
  public static final int ID = 20;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int DECIMAL = 15;
  public static final int EQUAL = 43;
  public static final int GREATER_EQUAL = 42;
  public static final int LEFT_SQUARE_BRACKET = 37;
  public static final int error = 1;
  public static final int SEMI_COLON = 47;
  public static final int DECREASE = 50;
  public static final int BREAK = 8;
  public static final int VOID = 2;
  public static final int EQUAL_TO = 44;
  public static final int SWITCH = 6;
  public static final int TIMES = 31;
  public static final int COLON = 48;
  public static final int ELSE = 5;
  public static final int WHILE = 11;
  public static final int DEFAULT = 9;
  public static final int STRING = 25;
  public static final int TEXT = 17;
  public static final int LESS_THAN = 39;
  public static final int RIGHT_CURLY_BRACKET = 36;
  public static final int LEFT_PARENTHESIS = 33;
  public static final int DO = 12;
  public static final int CONSOLE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "MAIN",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "FOR",
  "WHILE",
  "DO",
  "CONSOLE",
  "WRITE",
  "DECIMAL",
  "INTEGER",
  "TEXT",
  "CHARACTER",
  "BOOLEAN",
  "ID",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LEFT_PARENTHESIS",
  "RIGHT_PARENTHESIS",
  "LEFT_CURLY_BRACKET",
  "RIGHT_CURLY_BRACKET",
  "LEFT_SQUARE_BRACKET",
  "RIGHT_SQUARE_BRACKET",
  "LESS_THAN",
  "GREATER_THAN",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "EQUAL",
  "EQUAL_TO",
  "NOT_EQUAL_TO",
  "PERIOD",
  "SEMI_COLON",
  "COLON",
  "INCREASE",
  "DECREASE"
  };
}

