
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 13;
  public static final int PARENTESIS_ABIERTO = 3;
  public static final int DOLAR = 11;
  public static final int IGUAL = 12;
  public static final int CORCHETE_CERRADO = 8;
  public static final int MAYOR_QUE = 9;
  public static final int LETRA_MINUSCULA = 19;
  public static final int DOS_PUNTOS = 16;
  public static final int LLAVE_ABIERTA = 5;
  public static final int PARENTESIS_CERRADO = 4;
  public static final int COMA = 14;
  public static final int CARACTERES_ESPECIALES = 22;
  public static final int MENOR_QUE = 10;
  public static final int COMILLA_DOBLE = 17;
  public static final int EOF = 0;
  public static final int LETRA_MAYUSCULA = 20;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 18;
  public static final int PR_VOID = 2;
  public static final int LLAVE_CERRADA = 6;
  public static final int CORCHETE_ABIERTO = 7;
  public static final int PUNTO_Y_COMA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_VOID",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "MAYOR_QUE",
  "MENOR_QUE",
  "DOLAR",
  "IGUAL",
  "PUNTO",
  "COMA",
  "PUNTO_Y_COMA",
  "DOS_PUNTOS",
  "COMILLA_DOBLE",
  "IDENTIFICADOR",
  "LETRA_MINUSCULA",
  "LETRA_MAYUSCULA",
  "NUMERO",
  "CARACTERES_ESPECIALES"
  };
}

