
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 39;
  public static final int CHAR = 16;
  public static final int CORCHETE_CERRADO = 33;
  public static final int ENTERO = 47;
  public static final int CASE = 6;
  public static final int DOUBLE = 15;
  public static final int DOS_PUNTOS = 44;
  public static final int INT = 14;
  public static final int PARENTESIS_ABIERTO = 28;
  public static final int FOR = 9;
  public static final int LLAVE_ABIERTA = 30;
  public static final int WRITE = 13;
  public static final int IDENTIFICADOR = 51;
  public static final int NOT = 21;
  public static final int AND = 19;
  public static final int IGUAL = 36;
  public static final int TIPO_RETORNO = 2;
  public static final int CARACTER = 49;
  public static final int DISTINTO_QUE = 25;
  public static final int DIVIDIDO = 40;
  public static final int OR = 20;
  public static final int BOOL = 17;
  public static final int INCREMENTO = 22;
  public static final int IF = 3;
  public static final int PUNTO_COMA = 43;
  public static final int COMILLA_DOBLE = 45;
  public static final int DECIMAL = 46;
  public static final int CORCHETE_ABIERTO = 32;
  public static final int EOF = 0;
  public static final int DECREMENTO = 23;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int CADENA = 48;
  public static final int MENOS = 38;
  public static final int MENOR = 34;
  public static final int BREAK = 7;
  public static final int SWITCH = 5;
  public static final int MAYOR = 35;
  public static final int ELSE = 4;
  public static final int PUNTO = 41;
  public static final int WHILE = 10;
  public static final int IGUAL_QUE = 24;
  public static final int DEFAULT = 8;
  public static final int MAYOR_IGUAL = 27;
  public static final int BOOLEANO = 50;
  public static final int STRING = 18;
  public static final int PARENTESIS_CERRADO = 29;
  public static final int LLAVE_CERRADA = 31;
  public static final int MENOR_IGUAL = 26;
  public static final int DO = 11;
  public static final int CONSOLE = 12;
  public static final int MAS = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO_RETORNO",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "FOR",
  "WHILE",
  "DO",
  "CONSOLE",
  "WRITE",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING",
  "AND",
  "OR",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "IGUAL_QUE",
  "DISTINTO_QUE",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "PUNTO",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "COMILLA_DOBLE",
  "DECIMAL",
  "ENTERO",
  "CADENA",
  "CARACTER",
  "BOOLEANO",
  "IDENTIFICADOR"
  };
}

